name = "telegram-ilustre-control"
main = "index.mjs"
compatibility_date = "2026-07-01"

triggers = { crons = ["0 * * * *"] }

[[kv_namespaces]]
binding = "bot_config"
id = "16bf0a3e0ed54da7970b59316a23c540"

[vars]
GITHUB_OWNER = "ilustreai"
GITHUB_REPO = "noticias-catolicas"
GITHUB_REF = "main"
PUBLIC_SITE_URL = "https://noticias.ilustreai.com.br/"
CLOUDFLARE_ACCOUNT_ID = "062adc0e2e903f3e579f5d7e2a232bb8"
